[workspace]
resolver = "2"
members = [
    "bonfire",
    "bonfire-fcm",
    "bonfire-jwt",
]

[workspace.package]
edition = "2024"
rust-version = "1.89"
readme = "README.md"
repository = "https://github.com/Camper-CoolDie/bonfire-rust"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"
unreachable_pub = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
allow_attributes = "warn"
clone_on_ref_ptr = "warn"
deref_by_slicing = "warn"
module_name_repetitions = "warn"
partial_pub_fields = "warn"
self_named_module_files = "warn"
try_err = "warn"
struct_excessive_bools = { level = "allow", priority = 1 }
