mod change_follow;
mod get_curated_fandoms;
mod get_follows;
mod get_moderated_fandoms;
mod get_subscriptions;
mod set_age;
mod set_avatar;
mod set_background;
mod set_description;
mod set_gender;
mod set_link;
mod set_status;

pub(crate) use change_follow::ChangeFollowRequest;
pub(crate) use get_curated_fandoms::GetCuratedFandomsRequest;
pub(crate) use get_follows::GetFollowsRequest;
pub(crate) use get_moderated_fandoms::GetModeratedFandomsRequest;
pub(crate) use get_subscriptions::GetSubscriptionsRequest;
pub(crate) use set_age::SetAgeRequest;
pub(crate) use set_avatar::SetAvatarRequest;
pub(crate) use set_background::SetBackgroundRequest;
pub(crate) use set_description::SetDescriptionRequest;
pub(crate) use set_gender::SetGenderRequest;
pub(crate) use set_link::SetLinkRequest;
pub(crate) use set_status::SetStatusRequest;
