#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(
    feature = "serde",
    derive(Deserialize, Serialize),
    serde(rename_all = "snake_case")
)]
pub enum Kind {
    AccountActionRejected,
    AccountBanned,
    AccountFandomUnbanned,
    AccountFollowed,
    AccountMentioned,
    AccountTargetActionRejected,
    AccountUnfollowed,
    AchievementUnlocked,
    BlockRejected,
    ChatMessageCreated,
    ChatMessageEdited,
    ChatMessageRemoved,
    ChatMessageReplied,
    ChatRead,
    ChatTyping,
    CommentReplied,
    DonationProcessed,
    EffectApplied,
    EffectRemoved,
    FandomAccepted,
    FandomCuratorAssigned,
    FandomCuratorRevoked,
    FandomModeratorGranted,
    FandomModeratorRevoked,
    FandomRemovalRejected,
    FollowedPostCreated,
    ImportantPostCreated,
    PostClosed,
    PostDrafted,
    PostFandomChanged,
    PostImagesPurged,
    PostMultilingualDisabled,
    PostNsfwToggled,
    PostOpened,
    PostRelayPostCreated,
    PostRelayTurnAssigned,
    PostRelayTurnMissed,
    PostRelayTurnRejected,
    PostTagsChanged,
    ProfileDescriptionCleared,
    ProfileLinkRemoved,
    ProfileNameCleared,
    ProfileStatusCleared,
    PublicationBlocked,
    PublicationBlockedAfterReport,
    PublicationCommented,
    PublicationRated,
    PublicationReacted,
    PublicationRestored,
    PunishmentRemoved,
    RubricFandomChanged,
    RubricKarmaCoefChanged,
    RubricNameChanged,
    RubricOwnerAssigned,
    RubricOwnerTransferred,
    RubricRemoved,
    #[cfg_attr(feature = "serde", serde(untagged))]
    Unknown(i64),
}
