name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  style:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          profile: minimal
          override: true

      - name: Check rustfmt
        run: cargo fmt --check

  clippy:
    name: Check clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Protobuf compiler
        uses: arduino/setup-protoc@v3
        with:
          version: "34.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
      - uses: Swatinem/rust-cache@v2

      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  docs:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Protobuf compiler
        uses: arduino/setup-protoc@v3
        with:
          version: "34.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v2

      - name: Build docs
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: -D warnings

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up OpenSSL
        uses: johnwason/vcpkg-action@v7
        with:
          pkgs: openssl:x64-windows-static-md
          triplet: x64-windows
          token: ${{ github.token }}
        if: matrix.os == 'windows-latest'

      - name: Set OpenSSL installation path for openssl-sys crate
        run: |
          echo "OPENSSL_DIR=${{ github.workspace }}/vcpkg/installed/x64-windows-static-md" >> $env:GITHUB_ENV
          echo "OPENSSL_STATIC=1" >> $env:GITHUB_ENV
        if: matrix.os == 'windows-latest'

      - name: Set up Protobuf compiler
        uses: arduino/setup-protoc@v3
        with:
          version: "34.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all-features --verbose

  udeps:
    name: Check cargo-udeps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Protobuf compiler
        uses: arduino/setup-protoc@v3
        with:
          version: "34.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-udeps
        uses: taiki-e/install-action@cargo-udeps

      - name: Check cargo-udeps
        run: cargo udeps --all-targets --all-features

  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Protobuf compiler
        uses: arduino/setup-protoc@v3
        with:
          version: "34.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get MSRV from package metadata
        id: msrv
        run: echo "version=$(yq '.package.rust-version' Cargo.toml)" >> $GITHUB_OUTPUT
      - name: Set up Rust ${{ steps.msrv.outputs.version }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.msrv.outputs.version }}
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2

      - name: Check MSRV
        run: cargo check --all-features
        env:
          RUSTFLAGS: -D warnings
